services:
  scylla-nam:
    image: scylladb/scylla:2025.1
    ports:
      - "9042:9042"
    restart: always
    command: --seeds=scylla-nam --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --api-address 0.0.0.0 --broadcast-address scylla-nam
    volumes:
      - ./dev/scylla/cassandra-rackdc.nam.properties:/etc/scylla/cassandra-rackdc.properties
      - ./dev/scylla/data/nam:/var/lib/scylla
      - ./dev/scylla/scylla.yaml:/etc/scylla/scylla.yaml
    networks:
      octo_network:

  scylla-eur:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=scylla-nam,scylla-eur --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --api-address 0.0.0.0 --broadcast-address scylla-eur
    volumes:
      - ./dev/scylla/cassandra-rackdc.eur.properties:/etc/scylla/cassandra-rackdc.properties
      - ./dev/scylla/data/eur:/var/lib/scylla
      - ./dev/scylla/scylla.yaml:/etc/scylla/scylla.yaml
    depends_on:
      - scylla-nam
    networks:
      octo_network:
  
  scylla-sam:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=scylla-nam,scylla-eur --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --api-address 0.0.0.0 --broadcast-address scylla-sam
    volumes:
      - ./dev/scylla/cassandra-rackdc.sam.properties:/etc/scylla/cassandra-rackdc.properties
      - ./dev/scylla/data/sam:/var/lib/scylla
      - ./dev/scylla/scylla.yaml:/etc/scylla/scylla.yaml
    depends_on:
      - scylla-nam
      - scylla-eur
    networks:
      octo_network:

  scylla-sas:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=scylla-nam,scylla-eur --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --api-address 0.0.0.0 --broadcast-address scylla-sas
    volumes:
      - ./dev/scylla/cassandra-rackdc.sas.properties:/etc/scylla/cassandra-rackdc.properties
      - ./dev/scylla/data/sas:/var/lib/scylla
      - ./dev/scylla/scylla.yaml:/etc/scylla/scylla.yaml
    depends_on:
      - scylla-nam
      - scylla-eur
      - scylla-sam
    networks:
      octo_network:

  scylla-eas:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=scylla-nam,scylla-eur --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --api-address 0.0.0.0 --broadcast-address scylla-eas
    volumes:
      - ./dev/scylla/cassandra-rackdc.eas.properties:/etc/scylla/cassandra-rackdc.properties
      - ./dev/scylla/data/eas:/var/lib/scylla
      - ./dev/scylla/scylla.yaml:/etc/scylla/scylla.yaml
    depends_on:
      - scylla-nam
      - scylla-eur
      - scylla-sam
      - scylla-sas
    networks:
      octo_network:

  scylla-ocn:
    image: scylladb/scylla:2025.1
    restart: always
    command: --seeds=scylla-nam,scylla-eur --smp 1 --memory 750M --overprovisioned 1 --developer-mode 1 --api-address 0.0.0.0 --broadcast-address scylla-ocn
    volumes:
      - ./dev/scylla/cassandra-rackdc.ocn.properties:/etc/scylla/cassandra-rackdc.properties
      - ./dev/scylla/data/ocn:/var/lib/scylla
      - ./dev/scylla/scylla.yaml:/etc/scylla/scylla.yaml
    depends_on:
      - scylla-nam
      - scylla-eur
      - scylla-sam
      - scylla-sas
      - scylla-eas
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "cqlsh --execute='describe keyspaces'"]
      interval: 15s
      timeout: 10s
      retries: 20
    networks:
      octo_network:

  scylla-load-keyspaces:
    image: scylladb/scylla:2025.1
    depends_on:
      scylla-ocn:
        condition: service_healthy
    volumes:
      - ./dev/scylla/scripts/init.cql:/init.cql
    entrypoint: ["/bin/bash", "-c", "echo Loading Scylla keyspaces... && cqlsh scylla-ocn -f /init.cql"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    networks:
      octo_network:

  msg-db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "4200:5432"
    volumes:
      - ./msg_pgdata:/var/lib/postgresql/data
    networks:
      octo_network:

  octocon-app:
    container_name: octocon-app
    build:
      context: .
      dockerfile: dev/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - app_build:/build
      - app_deps:/deps
      - .:/app
    user: root
    depends_on:
      scylla-ocn:
        condition: service_healthy
    networks:
      octo_network:

networks:
  octo_network:
    driver: bridge

volumes:
  app_build:
  app_deps: